### ISSUE TITLE
Help me, can you told me, what packages I must to patch for DSDT K55VD?

### ISSUE THREAD

**Issue by cobaohieu** [BetaDroid/Asus_K55vd-Hackintosh#1]
Help me, can you told me, what packages I must to patch for DSDT K55VD?
I'm using mac OS 10.13

**Comment by danielzarioiu** [comment]
Depends on what is working and not on your system. For example on mine: audio, battery and wifi

**Comment by cobaohieu** [comment]
I own ASUS K55VD i5 3210, and DSDT you patched not working correctly on 10.13

**Comment by danielzarioiu** [comment]
I don't know because I released the DSDT for Mac OS X 10.11.6 and I'm using it on macOS 10.12.5 without problem. Now I don't have time to test new versions of macOS because I'm using the pc to work and Apple change somethings every time. As I say, now I can't waste my time to understand what Apple changed on macOS 10.13 maybe in a few months I'll test the latest version of macOS.

**Comment by cobaohieu** [comment]
Thanks for replying me.
